### ISSUE TITLE
Let ScriptBlockPlus support the Sponge please.

### ISSUE THREAD

**Issue by zsn741656478** [yuttyann/ScriptBlockPlus#10]
https://docs.spongepowered.org/stable/ja/
I have been using the ScriptBlockPlus plugin since and I really like this plugin. But in order to use the module you must use Sponge. there are many Sponge users who need similar plugins. I hope that you can make a Sponge version of ScriptBlockPlus. This may be a rude request, sorry. I am using Google Translate and I hope you can understand it.

**Comment by yuttyann** [comment]
I have never developed with a sponge.
You may touch it in the future, but please do not expect too much.
