### ISSUE TITLE
ScriptBlockPlus can't recognize what's in rpgitem

### ISSUE THREAD

**Issue by Clexus** [yuttyann/ScriptBlockPlus#11]
if i have a stone called &4stone,and i have a rpgitem stone,it also called &4stone. the first stone can be consumed bute the rpg stone can't

**Comment by yuttyann** [comment]
Can you explain it a little more clearly?
――
I want information such as scripts that are set.

**Comment by Clexus** [comment]
for example /sbp interact create [$item:stone 1 &4stone] ,and I create a rpg stone, use /rpgitem stone display &4stone,this rpg stone can't be consumed,but if I use other plugins to modify its name to &4stone,it can be consumed again.
In addition, can you add the function of limiting the number of scripts used by just one player?
My version:1.8.8

**Comment by yuttyann** [comment]
I tried with the following plug-in, but it was executed successfully.
[https://www.spigotmc.org/resources/rpgitems.17549/]

↓ TEST commands. [ScriptBlockPlus v1.8.8] [RPGItems v3.8]
/rpgitem display stone &4stone 
/sbp interact create [$item:stone 1 &4stone] [@player TEST]
――
A color code that is not related to the item name may have been added.
Please try variously.

The following is an example.
/sbp interact create [$item:stone 1 &r&4stone] [@player TEST]
etc...
――
As a special method, you can use '@calc:' to limit the number of times a script is executed.
