### ISSUE TITLE
It's can't run on Paper

### ISSUE THREAD

**Issue by xiangxiangxiong9** [yuttyann/ScriptBlockPlus#12]
Paper version is 194 [MC 1.15.2],and the ScriptBlockPlus's version is 1.8.9.
When I update it from 1.8.1 to 1.8.9,our server can't not start,it's stuck in enabling.
When I change it to spigot,everything is well.
[Sorry,I can't understand Japanese and my english is poor]

**Comment by yuttyann** [comment]
I confirmed with [PaperMC1.15.2], but it was able to start normally.
Try to regenerate the setting file.

我通过[PaperMC1.15.2]进行了确认，但是它能够正常启动。
尝试重新生成设置文件。

**Comment by xiangxiangxiong9** [comment]
OK，I will try again tomorrow,because I just shutdown my computer.
[#Why do know I'm from China,,,]



---Original---

**Comment by xiangxiangxiong9** [comment]
[translated from Chinese] I just tried vault and scriptblockplus separately and found that it can be started. I found that it was because Yum [started normally after trying to append the ignore list]
#
[翻訳は中国語からです。]VaultとScript BlockPlusを単独で試してみましたが、起動できることが分かりました。私が発見したのはyum[リストを追加して無視してから正常に起動することを試みた]からです。

**Comment by xiangxiangxiong9** [comment]
[translated from Chinese] I just tried vault and scriptblockplus separately and found that it can be started. I found it was due to Yum [normal startup after trying to disable]
#
[翻訳は中国語からです。]VaultとScript BlockPlusを単独で試してみましたが、起動できることが分かりました。私が発見したのはyumの[無効化を試みた後に正常に起動します]からです。
