### ISSUE TITLE
Make the "@calc" recognize text

### ISSUE THREAD

**Issue by Clexus** [yuttyann/ScriptBlockPlus#14]
Otherwise, you can't tell which world the player is in
For example[@calc:%player_world% == one You are not in one!]But what I got was NumberFormatException "For input string: "two""

**Comment by yuttyann** [comment]
"@calc:" is an option that exists to compare numbers.
Character strings cannot be assigned.


It is technically possible to digitize and compare the world.
I'll consider it.

**Comment by yuttyann** [comment]
Added the specification to compare strings.

https://github.com/yuttyann/ScriptBlockPlus/commit/219fa0b7962138b19e745c0ea2a542f63f89f11d
