### ISSUE TITLE
変数名を中国語のファイルに正常に解析できない

### ISSUE THREAD

**Issue by nainiu233** [yuttyann/ScriptBlockPlus#18]
变量名无法正常别解析到中文语言文件中
![image](https://user-images.githubusercontent.com/36364025/84770584-680c0080-b00a-11ea-8387-543b58583a0f.png)
如图所示"%scripttype%"并没有被正常解析
我使用的是catserver
————————————————————————————
変数名を中国語のファイルに正常に解析できない
![image](https://user-images.githubusercontent.com/36364025/84770584-680c0080-b00a-11ea-8387-543b58583a0f.png)
図に示すように、「％scripttype％」は正常に解析されていません
catserverを使用しています
————————————————————————————
以上 此致敬礼
上に敬礼

**Comment by yuttyann** [comment]
Try using the variable "%actiontype%",
I'm no longer using that variable.
I have overlooked the settings of the language file, so I will update it later.

**Comment by yuttyann** [comment]
e3d807f090decf15d1556d5bc05f2966fa4931dc
