### ISSUE TITLE
can't execute luckperms command.

### ISSUE THREAD

**Issue by rainhon** [yuttyann/ScriptBlockPlus#19]
I'm using your plugin And found the problem that most parts of luckperms commands don't work.

spigotVersion:1.15.2
sbpVersion:v1.9.7
luckpermsVersion:5.1.26

the command result as UNKNOW COMMAND

then i read the source code and found dispatchCommand method for executing command.

after that, i remove this part of the code and it worked.

````
	@SuppressWarnings("deprecation")
	public static boolean dispatchCommand(@NotNull CommandSender sender, @Nullable Location location, @NotNull String command) {
		Validate.notNull(sender, "Sender cannot be null");
		Validate.notNull(command, "Command cannot be null");
		boolean isCommandSelector = isPlatform() && SBConfig.COMMAND_SELECTOR.getValue();
//		if (isCommandSelector && (isCBXXXorLater("1.13") || CommandSelector.isCommandPattern(command))) {
//			if (location == null) {
//				if (sender instanceof Player) {
//					location = ((Player) sender).getLocation().clone();
//				} else if (sender instanceof SBPlayer) {
//					location = ((SBPlayer) sender).getLocation().clone();
//				} else if (sender instanceof BlockCommandSender) {
//					location = ((BlockCommandSender) sender).getBlock().getLocation().clone();
//				} else if (sender instanceof CommandMinecart) {
//					location = ((CommandMinecart) sender).getLocation().clone();
//				}
//			}
//			if (location != null) {
//				return CommandSelector.getListener().executeCommand(sender, location, command);
//			}
//		}
		return Bukkit.dispatchCommand(sender, command.startsWith("/") ? command.substring(1) : command);
	}
````

so i'm wondering the purpose to execute command this way, and what happened if i jump throuth this way.

**Comment by yuttyann** [comment]
It is intended to be a command selector.
It is a method that can execute commands with specifications close to command blocks.

We will investigate the cause at a later date and fix the plugin.

**Comment by yuttyann** [comment]
As a result of investigation, the command implemented in LuckPerms is different from other plugins in how to implement it, so it is a difficult problem to solve.
By adding "*" to the initials of the command, we plan to take measures to disable the selector function and execute the command with the Bukkit API function. (Example: */lp info, *lp info)
