### ISSUE TITLE
[NEED HELP]How to use script:@bypassPERM @bypassGROUP and argv:hit...

### ISSUE THREAD

**Issue by xiangxiangxiong9** [yuttyann/ScriptBlockPlus#22]
How to use @bypassPERM and @bypassGROUP...I don't know if this is a mistake in my command...When I tried these,the plugin reported some error..
There are the logs...
![@bypassGROUP Server](https://user-images.githubusercontent.com/60531086/103773587-4174ec00-5066-11eb-9302-e9352c81e967.png)
![@bypassGROUP Client png](https://user-images.githubusercontent.com/60531086/103773590-433eaf80-5066-11eb-941c-65bb8257f80c.png)
![@bypassPERM  Client](https://user-images.githubusercontent.com/60531086/103773594-446fdc80-5066-11eb-828f-f8d7402c0f09.png)
![@bypassPERM Server](https://user-images.githubusercontent.com/60531086/103773599-45087300-5066-11eb-9f65-bd6866c27749.png)

And how to use /sbp hit ?

**Comment by yuttyann** [comment]
Thank you for reporting the bug.
We are currently investigating the cause of the problem.

For "/ sbp hit", you can execute the script when you hit a block with a projectile such as a snowball.

**Comment by xiangxiangxiong9** [comment]
#
OK, I'll wait for your good news and test / SBP hit on my server at the same time.
When this problem is solved, I will update my repo.
#

**Comment by yuttyann** [comment]
It's an option error, but it seems to be written incorrectly.

Correct grammar-> @bypassPERM:[/]&lt;Command&gt;[/World]&lt;/Node&gt;
Example -> @bypassPERM:say message/pe.rm.ssion.s

&gt;&gt;&gt; [Option Description](https://github.com/yuttyann/ScriptBlockPlus/wiki/%5BEN%5D-Option-Description) &lt;&lt;&lt;

**Comment by yuttyann** [comment]
Apparently, in MCBBS, some of the updated contents are omitted, so please use SpigotMC to check the updated contents.

SpigotMC -> https://www.spigotmc.org/resources/1-9-1-16-x-scriptblockplus-mechanics.78413/updates

**Comment by xiangxiangxiong9** [comment]
> Apparently, in MCBBS, some of the updated contents are omitted, so please use SpigotMC to check the updated contents.
> 
> SpigotMC -> https://www.spigotmc.org/resources/1-9-1-16-x-scriptblockplus-mechanics.78413/updates

Usually I look for updates in this repository…
SpigotMC? Sometimes I go up and have a look.

**Comment by xiangxiangxiong9** [comment]
> It's an option error, but it seems to be written incorrectly.
> 
> Correct grammar-> @bypassPERM:[/]<Command>[/World]</Node>
> Example -> @bypassPERM:say message/pe.rm.ssion.s
> 
> >>> [Option Description](https://github.com/yuttyann/ScriptBlockPlus/wiki/%5BEN%5D-Option-Description) <<<

I just test it.
when I set @bypassPERM:say message/minecraft.command.say,I got no permission message[ I'm sorry, but you don't have permission to...
 ].when I set @bypassPERM:say message/world/minecraft.command.say,the command is executed [ [xiangxiangxiong] message ]
@bypassGROUP also.When I use @bypassGROUP:say message/test,I got no permission message.When I use @bypassGROUP:say message/world/test,the command is executed.

**Comment by yuttyann** [comment]
The bug that does not work properly if the world name is not included is currently being fixed.
I think we can update it in the near future.

**Comment by xiangxiangxiong9** [comment]
> The bug that does not work properly if the world name is not included is currently being fixed.
> I think we can update it in the near future.

OK…I will update my repo sometime later…
>>_[Maybe I will learn SQLite]_

**Comment by yuttyann** [comment]
v2.0.5 has been released. 
https://github.com/yuttyann/ScriptBlockPlus/releases/tag/v2.0.5
