### ISSUE TITLE
A new option

### ISSUE THREAD

**Issue by MagmaBlock** [yuttyann/ScriptBlockPlus#34]
- I have a poor English so this issus is translate by google.  I left a Chinese original version which I don't know who to show     ;w;

**Is your feature request related to a problem? Please describe./問題の説明**  

Our server often uses script blocks to do something useful, but there is a problem that has plagued us for a long time
Sometimes we need to limit the times players execute each script block, but we never know what to do
The plugin already has the @amount parameter, but what it limited is the executed times of the block, not each player.
So now, we have to set a very large number for @cooldown to make script block only can be used once.

> 我们的服务器经常使用脚本方块来做一些很有用的功能，但是有一个问题长期困扰着我们。
> 有时我们需要限制每个玩家执行的脚本次数，但我们不知道该怎么做。
> 插件已经有了@amount这个参数，但是他限制的是每个脚本方块执行的次数，而不是每个玩家的。
> 因此现在我们不得不把@cooldown设置得非常大以便让脚本方块只能被使用一次。

**Describe the solution you'd like/何をしたいのか**  
if possible, It's best to add a new parameter like @playeramount, which limit players or not blocks
> 如果可以，最好能够新增一个参数像是@playeramount，限制玩家的执行次数。

**Additional context/備考**  
In fact, I tried to use @calc with %player_count%, but it seems that this variable cannot be used (see the picture below)
> 事实上，我有尝试使用@calc 配合 %player_count%，但是这个变量似乎无法使用（见下图）

![image](https://user-images.githubusercontent.com/61128045/129454814-23de3d5c-f18b-44d3-adc2-cc35c780707d.png)
![image](https://user-images.githubusercontent.com/61128045/129454823-2b4b7842-89d1-47bf-ab50-7738c29230aa.png)
![image](https://user-images.githubusercontent.com/61128045/129454834-1f78c85a-ee8d-47f4-8ae5-a475a71af7e4.png)

Thanks!

**Comment by yuttyann** [comment]
你应该已经能够做到这一点。

你可能错误地使用了"@calc: "选项。
下面是一个如何使用它的例子
如果脚本的执行次数少于1，那么命令将被执行。
```
/sbp interact create [@calc:%player_count% < 1] [@command heal <player>] 
```

**Comment by MagmaBlock** [comment]
非常感谢您    解决了困扰我们有一段时间的问题
再次感谢！ 我会再仔细了解了解 calc 这个部分
