### ISSUE TITLE
Can't successfully add script that costs mod items (or generic ones)

### ISSUE THREAD

**Issue by JenevieveShe** [yuttyann/ScriptBlockPlus#36]
**Describe the bug/不具合の概要**  
$item script can't properly cost generic items or mod items.

**Server/サーバー**  
Type: CatServer  
Version: 1.12.2  
Plugins: 
AuthMe
BanItem
CMILib
CoreProtect
EssentialsX
EssentialsXChat
EssentialsXProtect
EssentialsXSpawn
GroupManager
Holographic Displays
LockettePro
LuckPerms
MaxHealth
mcMMO
Multiverse
NeverLag
NoBuguppercaseLowercase
PlaceholderAPI
ProtocolLib
QuickShop
Residence
rpgitem reloaded
ScriptBlockPlus v2.1.1 JV8
Vault
VillageMarker
worldedit
worldguard

**To Reproduce/再現手順**  
Steps to reproduce the behavior: (Texts..)
I issued the command and succussfully attached the script to target block:
**/sbp interact create $item:5834 1** 
but when I interact with the target block, I was told that I didn't have the item **[AIR:0]** with the amount 1
I tried other item ids, but the plugin still tells me the same or just says I entered the values wrong,
but sometimes when I use certains item ids like double_plant:4,(rose bush) it works fine.
Please help? I need it to successfully cost unique items from the CustomNPC's mod.

**Expected behavior/期待される動作**  
It's supposed to successfully cost 1 (purple broken orb from CustomNPC's mod) every time a player interact with the script block.

**Screenshots/スクリーンショット**  
![2022-01-09_19 10 36](https://user-images.githubusercontent.com/40168288/148679787-7e183c5c-5074-4496-b7a6-a3e0ff86e2cc.png)

**Additional context/備考**  
If you need to, please contact me at my email: jenevieveshe@outlook.com

**Comment by yuttyann** [comment]
It is not possible to specify items that have been added by mods.
You can only specify items that are implemented in BukkitAPI.
