### ISSUE TITLE
OPを持つプレイヤーログイン時SSLHandshakeExceptionが出る

### ISSUE THREAD

**Issue by ShrkSoft** [yuttyann/ScriptBlockPlus#37]
ScriptBlockPlusの最新版(Ver 2.2.2)を使用しています。
OP権限を持つプレイヤーがログインした時サーバコンソールに以下の警告が出ます。
また、/sbp checkver をすると、Error occurred while checking new versionと表示され同じログが出ます。
Minecraftのバージョンは1.12.2です。
[WARNING] javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching xml.yuttyann44581.net found.
[WARNING] at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
[WARNING] at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
[WARNING] at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
[WARNING] at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
[WARNING] at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source)
[WARNING] at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source)
[WARNING] at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source)
[WARNING] at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
[WARNING] at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
[WARNING] at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
[WARNING] at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
[WARNING] at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
[WARNING] at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
[WARNING] at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
[WARNING] at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[WARNING] at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
[WARNING] at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
[WARNING] at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
[WARNING] at com.github.yuttyann.scriptblockplus.utils.FileUtils.getWebFile(FileUtils.java:116)
[WARNING] at com.github.yuttyann.scriptblockplus.Updater.getDocument(Updater.java:233)
[WARNING] at com.github.yuttyann.scriptblockplus.Updater.load(Updater.java:125)
[WARNING] at com.github.yuttyann.scriptblockplus.ScriptBlock.lambda$checkUpdate$1(ScriptBlock.java:182)
[WARNING] at com.github.yuttyann.scriptblockplus.ScriptBlock$$Lambda$1664.000000007EC62C90.run(Unknown Source)
[WARNING] at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[WARNING] at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[WARNING] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[WARNING] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[WARNING] at java.base/java.lang.Thread.run(Unknown Source)
[WARNING] Caused by:
[WARNING] java.security.cert.CertificateException: No subject alternative DNS name matching xml.yuttyann44581.net found.
[WARNING] at java.base/sun.security.util.HostnameChecker.matchDNS(Unknown Source)
[WARNING] at java.base/sun.security.util.HostnameChecker.match(Unknown Source)
[WARNING] at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(Unknown Source)
[WARNING] at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(Unknown Source)
[WARNING] at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
[WARNING] at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)

**Comment by yuttyann** [comment]
報告が遅くなり申し訳ございません。
アップデート情報を取得するサイト（配布サイトも含め）が不具合を起こしていたのが原因でした。
現在は修正されています。
