### ISSUE TITLE
WorldGuardのフラグが効かなくなる・右クリックの挙動が変になる

### ISSUE THREAD

**Issue by ShrkSoft** [yuttyann/ScriptBlockPlus#4]
ScriptBlockPlus Version 1.6.0を使用していますが、このバージョンを使うとWorldGuardで保護した領域のフラグが効かなくなり、例えば保護領域内のフラグ、useがfalse（この設定でドア等が開かなくなる）であってもドアが開いてしまい保護が無意味になってしまいます。
また、弓や食べ物などアイテムが何かしらにフォーカスを当てていないと使用出来ない不具合も起きています。
この問題は前の1.5.0では発生せず1.6.0にアップデートしてから問題が起きたため、修正をお願いします。

**Comment by yuttyann** [comment]
WorldGuardをあまり扱ったことが無いので、保護した際のコマンド、WorldGuardのバージョンなどを書いていただけると対応が早まるかもしれません。

**Comment by yuttyann** [comment]
v1.5.0 と照合して、原因になりそうなものを一通り修正してみました。
解決しているかどうか確認お願いします。
http://kisu.me/HJD

**Comment by yuttyann** [comment]
WorldGuardだけではなくクリックの機能に不具合が発生していたため、WGは関係ないと判断し修正後更新させていただきました。

https://github.com/yuttyann/ScriptBlockPlus/commit/92953d2998b6bfdd4012d231eae71bd0d734f7ba
