### ISSUE TITLE
ツールのアイテムを任意に設定したい

### ISSUE THREAD

**Issue by kotarobo** [yuttyann/ScriptBlockPlus#42]
時計・木の棒・本・ブレイズロッドがツールに設定されていますが、既に他のツールが利用している場合利用することが出来ません
アイテムを任意に設定できませんでしょうか

**Comment by yuttyann** [comment]
追加予定の機能ですが、現在後継プラグインを製作中なので少々アップデートが遅れます。
また、参考として競合しているプラグインを教えていただけると嬉しいです。

（簡易的にはなってしまいますが、個人用としてツールに利用するアイテムを変更したプラグインをお渡しすることも可能です。その場合はアイテムタイプの指定をお願いします。例: ScriptEditor = 矢.. 等）

**Comment by kotarobo** [comment]
わかりました！後継プラグイン楽しみです！

Slot Machineというプラグインがブレイズロッド固定だったのですが、先日アイテム変更に対応していただけました。
木の棒は変更できないわけではないのですが、GriefPreventionやWorldGuardなどは木の棒が標準の保護エリア調査ツールになっています
本はSBPを導入する前にChestCommandプラグインでメニューなどを開くためのツールとして設定していたため、使用できるようにアイテムを入れ替えるとなると周知や伴う作業コストが高すぎる為断念していました
ツールが無い場合でも利用できるので自分用に利用していたのですが、他のスタッフからは利用しにくいようで別のプラグインを利用している感じでした(不具合が多いプラグインなので移行したいのですが中々)

簡易対応助かります！
スタッフにアイテムを確認中です。

**Comment by kotarobo** [comment]
確認した所下記の感じだと嬉しいとのことです～
時計：そのまま
本：知恵の本(KnowledgeBook)
木の棒：矢(arrow)
ブレイズロッド：光の矢(spectral_arrow)

**Comment by yuttyann** [comment]
作りました。

[解凍してください。.zip](https://github.com/yuttyann/ScriptBlockPlus/files/9791490/default.zip)

**Comment by kotarobo** [comment]
動きました！ありがとうございますー！！
