### ISSUE TITLE
Sudden server lag

### ISSUE THREAD

**Issue by CuteLittleSky** [yuttyann/ScriptBlockPlus#44]
**Describe the bug/不具合の概要**  

**Server/サーバー**  
Type: Paper
Version: 1.19.3
Plugins: ScriptBlockPlus-2.2.5

**To Reproduce/再現手順**  
Sudden performance lag when the server is open normally (tps from 20 to 12-)
Spark Timings: https://spark.lucko.me/NlBtKJOBGM
This seems to be generated due to sbp

**Comment by yuttyann** [comment]
The cause of the problem is unknown, so the priority of response is lowered.
