### ISSUE TITLE
Bug report about the walk scripts.

### ISSUE THREAD

**Issue by AndyYu168** [yuttyann/ScriptBlockPlus#47]
**Describe the bug/不具合の概要**  
When adding a command to a "walk" scriptblock to teleport to another world, the command will be executed twice.

**Server/サーバー**  
Type: Spigot
Version: 1.19.2
Plugins: ScriptBlockPlus-2.2.5 

**To Reproduce/再現手順**  
- Create a new walk scriptblock, attach it with a "bypass" command to let player teleport to another world. The following command is an example:
- **/sbp walk create [@bypass /tppos 1919 114 514 world_nether]**
- When a player walk on this scriptblock, certainly he will be teleported, but the script will be executed twice.
- This has been confirmed because I set the `ConsoleLog` to true, it remains 2 logs in my log file.
- Only happens when teleporting to another world, if the destination is in the same world, this won't happen.

**Expected behavior/期待される動作**  
Of course I want it executed only once, suppose I add a "delay" to the teleport command (e.g. let my player waiting 3 seconds before teleporting) the "delay" will be counted twice too, which makes my players annoyed.

**Screenshots/スクリーンショット**  
N/A

**Additional context/備考**  
N/A

**Comment by yuttyann** [comment]
I haven't played the test yet, but I think it is probably reacting to an event that detects movement when teleporting a player.

It may take some time as we figure out how to deal with it.
