### ISSUE TITLE
On MC1.19 and above versions, redstore blocks (BlockPhysicsEvent) can cause a large performance issues

### ISSUE THREAD

**Issue by MagmaBlock** [yuttyann/ScriptBlockPlus#50]
**Describe the bug/不具合の概要**  
We just update our server from 1.18.1 to 1.20.1，use same config with ScriptBlockPlus，and this problem happened.
Only need very less amount of redstore blocks, a large performance issues can cause. （Like screenshot）

Spark Profile 1（On real server，100+ms ticks only）：https://spark.lucko.me/bdQDVMEuBI
Spark Profile 2（My local test）：https://spark.lucko.me/0wEngQ6AHe

This problem may be caused by:
https://github.com/yuttyann/ScriptBlockPlus/blob/1c2300b421843fd1b14ec3049fdcec435c3c8f57/src/main/java/com/github/yuttyann/scriptblockplus/listener/BlockListener.java#L76C10-L76C10

By the Utils.isCBXXXorLater("1.19")  and just update from 1.18 to 1.20, I guess this problem only on 1.19+ servers. 

```java
    @EventHandler(priority = EventPriority.HIGH)
    public void onBlockPhysicsEvent(BlockPhysicsEvent event) {
        var block = event.getBlock();
        if (Utils.isCBXXXorLater("1.19")) {
            call(block);
            for (int i = 0, l = FACES.length; i < l; i++) {
                var relative = block;
                do {
                    search(relative = relative.getRelative(FACES[i]));
                } while (relative.isBlockPowered() || relative.isBlockIndirectlyPowered());
            }
        } else {
            search(block);
        }
    }
```

**Server/サーバー**  
Type: Paper
Version: 1.20.1
Plugins: ScriptBlockPlus v2.2.6

**To Reproduce/再現手順**  
Like in screenshot. Any redstore blocks can call BlockPhysicsEvent

**Screenshots/スクリーンショット**  

![1692701687887](https://github.com/yuttyann/ScriptBlockPlus/assets/61128045/40432c21-ef4e-4a85-accb-3f142dd9ccb1)
![1692702003509](https://github.com/yuttyann/ScriptBlockPlus/assets/61128045/ad4e1221-ec04-4647-bd55-ab2f0c729a4d)

**Additional context/備考**  
or if a config to disable redstore functions? because some server likely only use the basic trigger (walk, interact, etc...)

**Comment by yuttyann** [comment]
The circuit-related specifications are complex and the official API is almost unusable, so the system has been designed in this way, but it is still a burden, so we are currently trying to decide whether to remove the functionality or provide an alternative solution.

**Comment by yuttyann** [comment]
fix
