### ISSUE TITLE
JDK8 version condition problem problem

### ISSUE THREAD

**Issue by XiaoJie-150** [yuttyann/ScriptBlockPlus#51]
**Describe the bug/不具合の概要**  
I use the @IF method, he reports errors in the background, java.lang.nullpoIntterexception: Option [@IF % VAULT_ECO_BALANCE %> = 5000] DOES Not Exist

**Server/サーバー**  
Type: paper
Version: 1.12.2
Plugins: (For example ScriptBlockPlus-2.1.1-JV8 / ProtocolLib-4.4.0 etc...)

**To Reproduce/再現手順**  
Steps to reproduce the behavior: (Texts..)
Use [@if] script

**Expected behavior/期待される動作**  
Insufficient prompt conditions or execution instructions

**Screenshots/スクリーンショット**  

**Additional context/備考**

**Comment by yuttyann** [comment]
Use "@calc:" instead of "@if ".
